### ISSUE TITLE
debug模式下正常，打包apk时报错

### ISSUE THREAD

**Issue by shenqihailuoya** [jpush/jcore-react-native#18]
:jcore-react-native:packageReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Failed to capture snapshot of output files for task ':jcore-react-native:packageReleaseResources' property 'incrementalFolder' during up-to-date check.
> Could not read path 'C:\Users\Lenovo\Desktop\water\node_modules\jcore-react-native\android\build\intermediates\incremental\packageReleaseResources\merged.dir\values'.

**Comment by JoshLipan** [comment]
卸载 jcore 重新 install 试下
