### ISSUE TITLE
1.9.3 ios 编译不了, jcore-ios-2.7.1.a 应该命名为 libjcore-ios-2.7.1.a 才对

### ISSUE THREAD

**Issue by yinjun322** [jpush/jcore-react-native#47]
https://github.com/jpush/jcore-react-native/commit/e0232c8f92ae4881ae2057392adfc6a0cf7395fc#commitcomment-54447531

**Comment by yinjun322** [comment]
之前都是libjcore

**Comment by JoshLipan** [comment]
已更新v194
