### ISSUE TITLE
[JCOREInterface pushConfigController]: unrecognized selector sent to class 0x101a4d080

### ISSUE THREAD

**Issue by zcgong** [jpush/jcore-react-native#9]
[JPUSHService setupWithOption:launchOptions appKey:appKey
                        channel:channel apsForProduction:isProduction];
launchOptions: nil;
appKey: @"^^^^^^^^^^";
channel: @"";
isProduction: true;

this got exception  NSInvalidArgumentException

**Comment by huangminlinux** [comment]
这个问题一般是 jcore-react-native 和 jpush-react-native 版本不匹配导致。可以讲两个插件升级到最新版本
